feat: add app splash screen
CreativeSystem/HoneyPots pull request #5
Opened 2020-09-05 20:28 UTC by leoferreiralima

Adicionado a Splash Screen e algumas melhorias no layout

### Splash Screen Padrão: 
![image](https://user-images.githubusercontent.com/36305985/92313021-0621be00-ef9d-11ea-86b1-9a46cf8b8937.png)

### Splash Screen Dark Mode:
![image](https://user-images.githubusercontent.com/36305985/92313028-18036100-ef9d-11ea-98f2-860ad7d4aec9.png)

2020-09-05 20:55 UTC, ElielC requested changes

2020-09-05 20:55 UTC, ElielC commented on mobile/app/src/main/java/br/com/creative/honeypots/MainActivity.kt
> +class MainActivity : BaseActivity() {
por que BaseActivity?

2020-09-05 20:55 UTC, ElielC commented on mobile/app/src/main/java/br/com/creative/honeypots/presentation/BaseActivity.kt
> +open class BaseActivity : AppCompatActivity() {
e aqui AppCompatActivity

2020-09-05 20:55 UTC, ElielC commented on mobile/app/src/main/res/values-night/colors.xml
> +    <color name="backgroundSplash">@color/background</color>
não e mais facil colocar a cor

2020-09-05 20:55 UTC, ElielC commented on mobile/app/src/main/res/values-night/styles.xml
> +
não precisa de um theme no values-night se ele e igual no values

2020-09-06 11:11 UTC, leoferreiralima commented on mobile/app/src/main/java/br/com/creative/honeypots/MainActivity.kt
> +class MainActivity : BaseActivity() {
A base activity vai ter funcionalidades padrões em todas as telas e ou funções comuns como por exemplo esconter o menu ou algo do tipo.

2020-09-06 11:12 UTC, leoferreiralima commented on mobile/app/src/main/java/br/com/creative/honeypots/presentation/BaseActivity.kt
> +open class BaseActivity : AppCompatActivity() {
A BaseActivity extende de AppCompatActivity, aqui pode colocar codígos comuns entre todas as telas

2020-09-06 11:13 UTC, leoferreiralima commented on mobile/app/src/main/res/values-night/colors.xml
> +    <color name="backgroundSplash">@color/background</color>
faz sentido vou fazer essa alteração

2020-09-06 11:14 UTC, leoferreiralima commented on mobile/app/src/main/res/values-night/styles.xml
> +
realmente esqueci desse detalhe

2020-09-06 11:49 UTC, merged